# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            R tips and tricks
tagline:          'An R blog'
description:      'Created by <a href="mailto:afragos1@itam.mx">Antonio Fragoso</a> a Data Scientist student at <a href="http:www.itam.mx">ITAM</a>'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
